"""Python port of KaTeX's functions/symbolsSpacing.js - spacing symbol handling."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..build_common import make_ord, make_span, mathsym
from ..define_function import define_function_builders
from ..mathml_tree import MathNode, TextNode
from ..parse_error import ParseError

if TYPE_CHECKING:
    from ..options import Options
    from ..parse_node import ParseNode

# CSS-based spacing functions to their CSS class
CSS_SPACE = {
    "\\nobreak": "nobreak",
    "\\allowbreak": "allowbreak",
}

# Regular space characters with optional className
REGULAR_SPACE = {
    " ": {},
    "\\ ": {},
    "~": {"className": "nobreak"},
    "\\space": {},
    "\\nobreakspace": {"className": "nobreak"},
}

# Spacing symbols
define_function_builders({
    "type": "spacing",
    "html_builder": lambda group, options: _spacing_html_builder(group, options),
    "mathml_builder": lambda group, options: _spacing_mathml_builder(group, options),
})


def _spacing_html_builder(group: ParseNode, options: Options):
    """Build HTML for spacing symbols."""
    text = group["text"]

    if text in REGULAR_SPACE:
        class_name = REGULAR_SPACE[text].get("className", "")
        # Spaces are generated by adding an actual space
        if group["mode"] == "text":
            ord_elem = make_ord(group, options, "textord")
            if class_name:
                ord_elem.classes.append(class_name)
            return ord_elem
        else:
            return make_span(["mspace", class_name],
                           [mathsym(text, group["mode"], options)],
                           options)

    elif text in CSS_SPACE:
        # Spaces based on just a CSS class
        return make_span(["mspace", CSS_SPACE[text]], [], options)

    else:
        raise ParseError(f'Unknown type of space "{text}"')


def _spacing_mathml_builder(group: ParseNode, options: Options) -> MathNode:
    """Build MathML for spacing symbols."""
    text = group["text"]

    if text in REGULAR_SPACE:
        # Use non-breaking space character
        node = MathNode("mtext", [TextNode("\u00a0")])
    elif text in CSS_SPACE:
        # CSS-based MathML spaces are ignored
        node = MathNode("mspace")
    else:
        raise ParseError(f'Unknown type of space "{text}"')

    return node
