# Auto-generated from src/macros.js
MACROS_DATA = {
  "\\\\@ifstar": "\\\\@ifnextchar *{\\\\@firstoftwo{#1}}",
  "\\\\bgroup": "{",
  "\\\\egroup": "}",
  "~": "\\\\nobreakspace",
  "\\\\lq": "`",
  "\\\\rq": "'",
  "\\\\aa": "\\\\r a",
  "\\\\AA": "\\\\r A",
  "\\\\textcopyright": "\\\\html@mathml{\\\\textcircled{c}}{\\\\char`©}",
  "\\\\copyright": "\\\\TextOrMath{\\\\textcopyright}{\\\\text{\\\\textcopyright}}",
  "\\\\textregistered": "\\\\html@mathml{\\\\textcircled{\\\\scriptsize R}}{\\\\char`®}",
  "\\u212C": "\\\\mathscr{B}",
  "\\u2130": "\\\\mathscr{E}",
  "\\u2131": "\\\\mathscr{F}",
  "\\u210B": "\\\\mathscr{H}",
  "\\u2110": "\\\\mathscr{I}",
  "\\u2112": "\\\\mathscr{L}",
  "\\u2133": "\\\\mathscr{M}",
  "\\u211B": "\\\\mathscr{R}",
  "\\u212D": "\\\\mathfrak{C}",
  "\\u210C": "\\\\mathfrak{H}",
  "\\u2128": "\\\\mathfrak{Z}",
  "\\\\Bbbk": "\\\\Bbb{k}",
  "\\u00b7": "\\\\cdotp",
  "\\\\llap": "\\\\mathllap{\\\\textrm{#1}}",
  "\\\\rlap": "\\\\mathrlap{\\\\textrm{#1}}",
  "\\\\clap": "\\\\mathclap{\\\\textrm{#1}}",
  "\\\\mathstrut": "\\\\vphantom{(}",
  "\\\\underbar": "\\\\underline{\\\\text{#1}}",
  "\\\\neq": "\\\\html@mathml{\\\\mathrel{\\\\not=}}{\\\\mathrel{\\\\char`≠}}",
  "\\\\ne": "\\\\neq",
  "\\u2260": "\\\\neq",
  "\\u2209": "\\\\notin",
  "\\u2259": "\\\\html@mathml{\\\\stackrel{\\\\tiny\\\\wedge}{=}}{\\\\mathrel{\\\\char`\\u2258}}",
  "\\u225A": "\\\\html@mathml{\\\\stackrel{\\\\tiny\\\\vee}{=}}{\\\\mathrel{\\\\char`\\u225A}}",
  "\\u225F": "\\\\html@mathml{\\\\stackrel{\\\\tiny?}{=}}{\\\\mathrel{\\\\char`\\u225F}}",
  "\\u27C2": "\\\\perp",
  "\\u203C": "\\\\mathclose{!\\\\mkern-0.8mu!}",
  "\\u220C": "\\\\notni",
  "\\u231C": "\\\\ulcorner",
  "\\u231D": "\\\\urcorner",
  "\\u231E": "\\\\llcorner",
  "\\u231F": "\\\\lrcorner",
  "\\u00A9": "\\\\copyright",
  "\\u00AE": "\\\\textregistered",
  "\\uFE0F": "\\\\textregistered",
  "\\\\vdots": "{\\\\varvdots\\\\rule{0pt}{15pt}}",
  "\\u22ee": "\\\\vdots",
  "\\\\varGamma": "\\\\mathit{\\\\Gamma}",
  "\\\\varDelta": "\\\\mathit{\\\\Delta}",
  "\\\\varTheta": "\\\\mathit{\\\\Theta}",
  "\\\\varLambda": "\\\\mathit{\\\\Lambda}",
  "\\\\varXi": "\\\\mathit{\\\\Xi}",
  "\\\\varPi": "\\\\mathit{\\\\Pi}",
  "\\\\varSigma": "\\\\mathit{\\\\Sigma}",
  "\\\\varUpsilon": "\\\\mathit{\\\\Upsilon}",
  "\\\\varPhi": "\\\\mathit{\\\\Phi}",
  "\\\\varPsi": "\\\\mathit{\\\\Psi}",
  "\\\\varOmega": "\\\\mathit{\\\\Omega}",
  "\\\\substack": "\\\\begin{subarray}{c}#1\\\\end{subarray}",
  "\\\\boxed": "\\\\fbox{$\\\\displaystyle{#1}$}",
  "\\\\iff": "\\\\DOTSB\\\\;\\\\Longleftrightarrow\\\\;",
  "\\\\implies": "\\\\DOTSB\\\\;\\\\Longrightarrow\\\\;",
  "\\\\impliedby": "\\\\DOTSB\\\\;\\\\Longleftarrow\\\\;",
  "\\\\dddot": "{\\\\overset{\\\\raisebox{-0.1ex}{\\\\normalsize ...}}{#1}}",
  "\\\\ddddot": "{\\\\overset{\\\\raisebox{-0.1ex}{\\\\normalsize ....}}{#1}}",
  "\\\\dotsb": "\\\\cdots",
  "\\\\dotsm": "\\\\cdots",
  "\\\\dotsi": "\\\\!\\\\cdots",
  "\\\\dotsx": "\\\\ldots\\\\,",
  "\\\\DOTSI": "\\\\relax",
  "\\\\DOTSB": "\\\\relax",
  "\\\\DOTSX": "\\\\relax",
  "\\\\tmspace": "\\\\TextOrMath{\\\\kern#1#3}{\\\\mskip#1#2}\\\\relax",
  "\\\\,": "\\\\tmspace+{3mu}{.1667em}",
  "\\\\thinspace": "\\\\,",
  "\\\\>": "\\\\mskip{4mu}",
  "\\\\:": "\\\\tmspace+{4mu}{.2222em}",
  "\\\\medspace": "\\\\:",
  "\\\\;": "\\\\tmspace+{5mu}{.2777em}",
  "\\\\thickspace": "\\\\;",
  "\\\\!": "\\\\tmspace-{3mu}{.1667em}",
  "\\\\negthinspace": "\\\\!",
  "\\\\negmedspace": "\\\\tmspace-{4mu}{.2222em}",
  "\\\\negthickspace": "\\\\tmspace-{5mu}{.277em}",
  "\\\\enspace": "\\\\kern.5em ",
  "\\\\enskip": "\\\\hskip.5em\\\\relax",
  "\\\\quad": "\\\\hskip1em\\\\relax",
  "\\\\qquad": "\\\\hskip2em\\\\relax",
  "\\\\tag": "\\\\@ifstar\\\\tag@literal\\\\tag@paren",
  "\\\\tag@paren": "\\\\tag@literal{({#1})}",
  "\\\\pmod": "\\\\pod{{\\\\rm mod}\\\\mkern6mu#1}",
  "\\\\newline": "\\\\\\\\\\\\relax",
  "\\\\hspace": "\\\\@ifstar\\\\@hspacer\\\\@hspace",
  "\\\\@hspace": "\\\\hskip #1\\\\relax",
  "\\\\@hspacer": "\\\\rule{0pt}{0pt}\\\\hskip #1\\\\relax",
  "\\\\ordinarycolon": ":",
  "\\\\vcentcolon": "\\\\mathrel{\\\\mathop\\\\ordinarycolon}",
  "\\u2237": "\\\\dblcolon",
  "\\u2239": "\\\\eqcolon",
  "\\u2254": "\\\\coloneqq",
  "\\u2255": "\\\\eqqcolon",
  "\\u2A74": "\\\\Coloneqq",
  "\\\\ratio": "\\\\vcentcolon",
  "\\\\coloncolon": "\\\\dblcolon",
  "\\\\colonequals": "\\\\coloneqq",
  "\\\\coloncolonequals": "\\\\Coloneqq",
  "\\\\equalscolon": "\\\\eqqcolon",
  "\\\\equalscoloncolon": "\\\\Eqqcolon",
  "\\\\colonminus": "\\\\coloneq",
  "\\\\coloncolonminus": "\\\\Coloneq",
  "\\\\minuscolon": "\\\\eqcolon",
  "\\\\minuscoloncolon": "\\\\Eqcolon",
  "\\\\coloncolonapprox": "\\\\Colonapprox",
  "\\\\coloncolonsim": "\\\\Colonsim",
  "\\\\simcolon": "\\\\mathrel{\\\\sim\\\\mathrel{\\\\mkern-1.2mu}\\\\vcentcolon}",
  "\\\\simcoloncolon": "\\\\mathrel{\\\\sim\\\\mathrel{\\\\mkern-1.2mu}\\\\dblcolon}",
  "\\\\approxcolon": "\\\\mathrel{\\\\approx\\\\mathrel{\\\\mkern-1.2mu}\\\\vcentcolon}",
  "\\\\approxcoloncolon": "\\\\mathrel{\\\\approx\\\\mathrel{\\\\mkern-1.2mu}\\\\dblcolon}",
  "\\\\notni": "\\\\html@mathml{\\\\not\\\\ni}{\\\\mathrel{\\\\char`\\u220C}}",
  "\\\\limsup": "\\\\DOTSB\\\\operatorname*{lim\\\\,sup}",
  "\\\\liminf": "\\\\DOTSB\\\\operatorname*{lim\\\\,inf}",
  "\\\\injlim": "\\\\DOTSB\\\\operatorname*{inj\\\\,lim}",
  "\\\\projlim": "\\\\DOTSB\\\\operatorname*{proj\\\\,lim}",
  "\\\\varlimsup": "\\\\DOTSB\\\\operatorname*{\\\\overline{lim}}",
  "\\\\varliminf": "\\\\DOTSB\\\\operatorname*{\\\\underline{lim}}",
  "\\\\varinjlim": "\\\\DOTSB\\\\operatorname*{\\\\underrightarrow{lim}}",
  "\\\\varprojlim": "\\\\DOTSB\\\\operatorname*{\\\\underleftarrow{lim}}",
  "\\\\gvertneqq": "\\\\html@mathml{\\\\@gvertneqq}{\\u2269}",
  "\\\\lvertneqq": "\\\\html@mathml{\\\\@lvertneqq}{\\u2268}",
  "\\\\ngeqq": "\\\\html@mathml{\\\\@ngeqq}{\\u2271}",
  "\\\\ngeqslant": "\\\\html@mathml{\\\\@ngeqslant}{\\u2271}",
  "\\\\nleqq": "\\\\html@mathml{\\\\@nleqq}{\\u2270}",
  "\\\\nleqslant": "\\\\html@mathml{\\\\@nleqslant}{\\u2270}",
  "\\\\nshortmid": "\\\\html@mathml{\\\\@nshortmid}{∤}",
  "\\\\nshortparallel": "\\\\html@mathml{\\\\@nshortparallel}{∦}",
  "\\\\nsubseteqq": "\\\\html@mathml{\\\\@nsubseteqq}{\\u2288}",
  "\\\\nsupseteqq": "\\\\html@mathml{\\\\@nsupseteqq}{\\u2289}",
  "\\\\varsubsetneq": "\\\\html@mathml{\\\\@varsubsetneq}{⊊}",
  "\\\\varsubsetneqq": "\\\\html@mathml{\\\\@varsubsetneqq}{⫋}",
  "\\\\varsupsetneq": "\\\\html@mathml{\\\\@varsupsetneq}{⊋}",
  "\\\\varsupsetneqq": "\\\\html@mathml{\\\\@varsupsetneqq}{⫌}",
  "\\\\imath": "\\\\html@mathml{\\\\@imath}{\\u0131}",
  "\\\\jmath": "\\\\html@mathml{\\\\@jmath}{\\u0237}",
  "\\u27e6": "\\\\llbracket",
  "\\u27e7": "\\\\rrbracket",
  "\\u2983": "\\\\lBrace",
  "\\u2984": "\\\\rBrace",
  "⦵": "\\\\minuso",
  "\\\\darr": "\\\\downarrow",
  "\\\\dArr": "\\\\Downarrow",
  "\\\\Darr": "\\\\Downarrow",
  "\\\\lang": "\\\\langle",
  "\\\\rang": "\\\\rangle",
  "\\\\uarr": "\\\\uparrow",
  "\\\\uArr": "\\\\Uparrow",
  "\\\\Uarr": "\\\\Uparrow",
  "\\\\N": "\\\\mathbb{N}",
  "\\\\R": "\\\\mathbb{R}",
  "\\\\Z": "\\\\mathbb{Z}",
  "\\\\alef": "\\\\aleph",
  "\\\\alefsym": "\\\\aleph",
  "\\\\Alpha": "\\\\mathrm{A}",
  "\\\\Beta": "\\\\mathrm{B}",
  "\\\\bull": "\\\\bullet",
  "\\\\Chi": "\\\\mathrm{X}",
  "\\\\clubs": "\\\\clubsuit",
  "\\\\cnums": "\\\\mathbb{C}",
  "\\\\Complex": "\\\\mathbb{C}",
  "\\\\Dagger": "\\\\ddagger",
  "\\\\diamonds": "\\\\diamondsuit",
  "\\\\empty": "\\\\emptyset",
  "\\\\Epsilon": "\\\\mathrm{E}",
  "\\\\Eta": "\\\\mathrm{H}",
  "\\\\exist": "\\\\exists",
  "\\\\harr": "\\\\leftrightarrow",
  "\\\\hArr": "\\\\Leftrightarrow",
  "\\\\Harr": "\\\\Leftrightarrow",
  "\\\\hearts": "\\\\heartsuit",
  "\\\\image": "\\\\Im",
  "\\\\infin": "\\\\infty",
  "\\\\Iota": "\\\\mathrm{I}",
  "\\\\isin": "\\\\in",
  "\\\\Kappa": "\\\\mathrm{K}",
  "\\\\larr": "\\\\leftarrow",
  "\\\\lArr": "\\\\Leftarrow",
  "\\\\Larr": "\\\\Leftarrow",
  "\\\\lrarr": "\\\\leftrightarrow",
  "\\\\lrArr": "\\\\Leftrightarrow",
  "\\\\Lrarr": "\\\\Leftrightarrow",
  "\\\\Mu": "\\\\mathrm{M}",
  "\\\\natnums": "\\\\mathbb{N}",
  "\\\\Nu": "\\\\mathrm{N}",
  "\\\\Omicron": "\\\\mathrm{O}",
  "\\\\plusmn": "\\\\pm",
  "\\\\rarr": "\\\\rightarrow",
  "\\\\rArr": "\\\\Rightarrow",
  "\\\\Rarr": "\\\\Rightarrow",
  "\\\\real": "\\\\Re",
  "\\\\reals": "\\\\mathbb{R}",
  "\\\\Reals": "\\\\mathbb{R}",
  "\\\\Rho": "\\\\mathrm{P}",
  "\\\\sdot": "\\\\cdot",
  "\\\\sect": "\\\\S",
  "\\\\spades": "\\\\spadesuit",
  "\\\\sub": "\\\\subset",
  "\\\\sube": "\\\\subseteq",
  "\\\\supe": "\\\\supseteq",
  "\\\\Tau": "\\\\mathrm{T}",
  "\\\\thetasym": "\\\\vartheta",
  "\\\\varcoppa": "\\\\\\mbox{\\\\coppa}",
  "\\\\weierp": "\\\\wp",
  "\\\\Zeta": "\\\\mathrm{Z}",
  "\\\\argmin": "\\\\DOTSB\\\\operatorname*{arg\\\\,min}",
  "\\\\argmax": "\\\\DOTSB\\\\operatorname*{arg\\\\,max}",
  "\\\\plim": "\\\\DOTSB\\\\mathop{\\\\operatorname{plim}}\\\\limits",
  "\\\\bra": "\\\\mathinner{\\\\langle{#1}|}",
  "\\\\ket": "\\\\mathinner{|{#1}\\\\rangle}",
  "\\\\braket": "\\\\mathinner{\\\\langle{#1}\\\\rangle}",
  "\\\\Bra": "\\\\left\\\\langle#1\\\\right|",
  "\\\\Ket": "\\\\left|#1\\\\right\\\\rangle",
  "\\\\set": "\\\\bra@set{\\\\{\\\\,}{\\\\mid}{}{\\\\,\\\\}}",
  "\\\\angln": "{\\\\angl n}",
  "\\\\blue": "\\\\textcolor{##6495ed}{#1}",
  "\\\\orange": "\\\\textcolor{##ffa500}{#1}",
  "\\\\pink": "\\\\textcolor{##ff00af}{#1}",
  "\\\\red": "\\\\textcolor{##df0030}{#1}",
  "\\\\green": "\\\\textcolor{##28ae7b}{#1}",
  "\\\\gray": "\\\\textcolor{gray}{#1}",
  "\\\\purple": "\\\\textcolor{##9d38bd}{#1}",
  "\\\\blueA": "\\\\textcolor{##ccfaff}{#1}",
  "\\\\blueB": "\\\\textcolor{##80f6ff}{#1}",
  "\\\\blueC": "\\\\textcolor{##63d9ea}{#1}",
  "\\\\blueD": "\\\\textcolor{##11accd}{#1}",
  "\\\\blueE": "\\\\textcolor{##0c7f99}{#1}",
  "\\\\tealA": "\\\\textcolor{##94fff5}{#1}",
  "\\\\tealB": "\\\\textcolor{##26edd5}{#1}",
  "\\\\tealC": "\\\\textcolor{##01d1c1}{#1}",
  "\\\\tealD": "\\\\textcolor{##01a995}{#1}",
  "\\\\tealE": "\\\\textcolor{##208170}{#1}",
  "\\\\greenA": "\\\\textcolor{##b6ffb0}{#1}",
  "\\\\greenB": "\\\\textcolor{##8af281}{#1}",
  "\\\\greenC": "\\\\textcolor{##74cf70}{#1}",
  "\\\\greenD": "\\\\textcolor{##1fab54}{#1}",
  "\\\\greenE": "\\\\textcolor{##0d923f}{#1}",
  "\\\\goldA": "\\\\textcolor{##ffd0a9}{#1}",
  "\\\\goldB": "\\\\textcolor{##ffbb71}{#1}",
  "\\\\goldC": "\\\\textcolor{##ff9c39}{#1}",
  "\\\\goldD": "\\\\textcolor{##e07d10}{#1}",
  "\\\\goldE": "\\\\textcolor{##a75a05}{#1}",
  "\\\\redA": "\\\\textcolor{##fca9a9}{#1}",
  "\\\\redB": "\\\\textcolor{##ff8482}{#1}",
  "\\\\redC": "\\\\textcolor{##f9685d}{#1}",
  "\\\\redD": "\\\\textcolor{##e84d39}{#1}",
  "\\\\redE": "\\\\textcolor{##bc2612}{#1}",
  "\\\\maroonA": "\\\\textcolor{##ffbde0}{#1}",
  "\\\\maroonB": "\\\\textcolor{##ff92c6}{#1}",
  "\\\\maroonC": "\\\\textcolor{##ed5fa6}{#1}",
  "\\\\maroonD": "\\\\textcolor{##ca337c}{#1}",
  "\\\\maroonE": "\\\\textcolor{##9e034e}{#1}",
  "\\\\purpleA": "\\\\textcolor{##ddd7ff}{#1}",
  "\\\\purpleB": "\\\\textcolor{##c6b9fc}{#1}",
  "\\\\purpleC": "\\\\textcolor{##aa87ff}{#1}",
  "\\\\purpleD": "\\\\textcolor{##7854ab}{#1}",
  "\\\\purpleE": "\\\\textcolor{##543b78}{#1}",
  "\\\\mintA": "\\\\textcolor{##f5f9e8}{#1}",
  "\\\\mintB": "\\\\textcolor{##edf2df}{#1}",
  "\\\\mintC": "\\\\textcolor{##e0e5cc}{#1}",
  "\\\\grayA": "\\\\textcolor{##f6f7f7}{#1}",
  "\\\\grayB": "\\\\textcolor{##f0f1f2}{#1}",
  "\\\\grayC": "\\\\textcolor{##e3e5e6}{#1}",
  "\\\\grayD": "\\\\textcolor{##d6d8da}{#1}",
  "\\\\grayE": "\\\\textcolor{##babec2}{#1}",
  "\\\\grayF": "\\\\textcolor{##888d93}{#1}",
  "\\\\grayG": "\\\\textcolor{##626569}{#1}",
  "\\\\grayH": "\\\\textcolor{##3b3e40}{#1}",
  "\\\\grayI": "\\\\textcolor{##21242c}{#1}",
  "\\\\kaBlue": "\\\\textcolor{##314453}{#1}",
  "\\\\kaGreen": "\\\\textcolor{##71B307}{#1}",
  "\\\\noexpand": "<function macro>",
  "\\\\expandafter": "<function macro>",
  "\\\\@firstoftwo": "<function macro>",
  "\\\\@secondoftwo": "<function macro>",
  "\\\\@ifnextchar": "<function macro>",
  "\\\\TextOrMath": "<function macro>",
  "\\\\char": "<function macro>",
  "\\\\dots": "<function macro>",
  "\\\\dotso": "<function macro>",
  "\\\\dotsc": "<function macro>",
  "\\\\cdots": "<function macro>",
  "\\\\newcommand": "<unparsed macro>",
  "\\\\renewcommand": "<unparsed macro>",
  "\\\\providecommand": "<unparsed macro>",
  "\\\\message": "<unparsed macro>",
  "\\\\errmessage": "<unparsed macro>",
  "\\\\show": "<unparsed macro>",
  "\\\\not": "<unparsed macro>",
  "\\\\notin": "<unparsed macro>",
  "\\u2258": "<unparsed macro>",
  "\\u225B": "<unparsed macro>",
  "\\u225D": "<unparsed macro>",
  "\\u225E": "<unparsed macro>",
  "\\\\ulcorner": "<unparsed macro>",
  "\\\\urcorner": "<unparsed macro>",
  "\\\\llcorner": "<unparsed macro>",
  "\\\\lrcorner": "<unparsed macro>",
  "\\\\colon": "<unparsed macro>",
  "\\\\tag@literal": "<unparsed macro>",
  "\\\\bmod": "<unparsed macro>",
  "\\\\pod": "<unparsed macro>",
  "\\\\mod": "<unparsed macro>",
  "\\\\TeX": "<unparsed macro>",
  "\\\\LaTeX": "<unparsed macro>",
  "\\\\KaTeX": "<unparsed macro>",
  "\\\\dblcolon": "<unparsed macro>",
  "\\\\coloneqq": "<unparsed macro>",
  "\\\\Coloneqq": "<unparsed macro>",
  "\\\\coloneq": "<unparsed macro>",
  "\\\\Coloneq": "<unparsed macro>",
  "\\\\eqqcolon": "<unparsed macro>",
  "\\\\Eqqcolon": "<unparsed macro>",
  "\\\\eqcolon": "<unparsed macro>",
  "\\\\Eqcolon": "<unparsed macro>",
  "\\\\colonapprox": "<unparsed macro>",
  "\\\\Colonapprox": "<unparsed macro>",
  "\\\\colonsim": "<unparsed macro>",
  "\\\\Colonsim": "<unparsed macro>",
  "\\\\llbracket": "<unparsed macro>",
  "\\\\rrbracket": "<unparsed macro>",
  "\\\\lBrace": "<unparsed macro>",
  "\\\\rBrace": "<unparsed macro>",
  "\\\\minuso": "<unparsed macro>",
  "\\\\bra@ket": "<unparsed macro>",
  "\\\\bra@set": "<unparsed macro>",
  "\\\\Braket": "<unparsed macro>",
  "\\\\Set": "<unparsed macro>"
}
