# Auto-generated from KaTeX src/macros.js - DO NOT EDIT BY HAND
MACROS_DATA = {'\\@firstoftwo': '<function macro>',
 '\\@hspace': '\\hskip #1\\relax',
 '\\@hspacer': '\\rule{0pt}{0pt}\\hskip #1\\relax',
 '\\@ifnextchar': '<function macro>',
 '\\@ifstar': '\\@ifnextchar *{\\@firstoftwo{#1}}',
 '\\@secondoftwo': '<function macro>',
 '\\AA': '\\r A',
 '\\Alpha': '\\mathrm{A}',
 '\\Bbbk': '\\Bbb{k}',
 '\\Beta': '\\mathrm{B}',
 '\\Bra': '\\left\\langle#1\\right|',
 '\\Braket': '\\bra@ket{\\left\\langle}" +\n'
             '    '
             '"{\\,\\middle\\vert\\,}{\\,\\middle\\vert\\,}{\\right\\rangle}',
 '\\Chi': '\\mathrm{X}',
 '\\Colonapprox': '\\html@mathml{" +\n'
                  '    '
                  '"\\mathrel{\\dblcolon\\mathrel{\\mkern-1.2mu}\\approx}}" +\n'
                  '    "{\\mathop{\\char"2237\\char"2248}}',
 '\\Coloneq': '\\html@mathml{" +\n'
              '    '
              '"\\mathrel{\\dblcolon\\mathrel{\\mkern-1.2mu}\\mathrel{-}}}" +\n'
              '    "{\\mathop{\\char"2237\\char"2212}}',
 '\\Coloneqq': '\\html@mathml{" +\n'
               '    "\\mathrel{\\dblcolon\\mathrel{\\mkern-1.2mu}=}}" +\n'
               '    "{\\mathop{\\char"2237\\char"3d}}',
 '\\Colonsim': '\\html@mathml{" +\n'
               '    "\\mathrel{\\dblcolon\\mathrel{\\mkern-1.2mu}\\sim}}" +\n'
               '    "{\\mathop{\\char"2237\\char"223c}}',
 '\\Complex': '\\mathbb{C}',
 '\\Dagger': '\\ddagger',
 '\\Darr': '\\Downarrow',
 '\\Epsilon': '\\mathrm{E}',
 '\\Eqcolon': '\\html@mathml{" +\n'
              '    '
              '"\\mathrel{\\mathrel{-}\\mathrel{\\mkern-1.2mu}\\dblcolon}}" +\n'
              '    "{\\mathop{\\char"2212\\char"2237}}',
 '\\Eqqcolon': '\\html@mathml{" +\n'
               '    "\\mathrel{=\\mathrel{\\mkern-1.2mu}\\dblcolon}}" +\n'
               '    "{\\mathop{\\char"3d\\char"2237}}',
 '\\Eta': '\\mathrm{H}',
 '\\Harr': '\\Leftrightarrow',
 '\\Iota': '\\mathrm{I}',
 '\\KaTeX': '\\textrm{\\html@mathml{" +\n'
            '    `K\\kern-.17em\\raisebox{${latexRaiseA}}{\\scriptstyle A}` +\n'
            '    "\\kern-.15em\\TeX}{KaTeX}}',
 '\\Kappa': '\\mathrm{K}',
 '\\Ket': '\\left|#1\\right\\rangle',
 '\\LaTeX': '\\textrm{\\html@mathml{" +\n'
            '    `L\\kern-.36em\\raisebox{${latexRaiseA}}{\\scriptstyle A}` +\n'
            '    "\\kern-.15em\\TeX}{LaTeX}}',
 '\\Larr': '\\Leftarrow',
 '\\Lrarr': '\\Leftrightarrow',
 '\\Mu': '\\mathrm{M}',
 '\\N': '\\mathbb{N}',
 '\\Nu': '\\mathrm{N}',
 '\\Omicron': '\\mathrm{O}',
 '\\R': '\\mathbb{R}',
 '\\Rarr': '\\Rightarrow',
 '\\Reals': '\\mathbb{R}',
 '\\Rho': '\\mathrm{P}',
 '\\Set': '\\bra@set{\\left\\{\\:}" +\n'
          '    "{\\;\\middle\\vert\\;}{\\;\\middle\\Vert\\;}{\\:\\right\\}}',
 '\\Tau': '\\mathrm{T}',
 '\\TextOrMath': '<function macro>',
 '\\Uarr': '\\Uparrow',
 '\\Z': '\\mathbb{Z}',
 '\\Zeta': '\\mathrm{Z}',
 '\\aa': '\\r a',
 '\\alef': '\\aleph',
 '\\alefsym': '\\aleph',
 '\\angln': '{\\angl n}',
 '\\approxcolon': '\\mathrel{\\approx\\mathrel{\\mkern-1.2mu}\\vcentcolon}',
 '\\approxcoloncolon': '\\mathrel{\\approx\\mathrel{\\mkern-1.2mu}\\dblcolon}',
 '\\argmax': '\\DOTSB\\operatorname*{arg\\,max}',
 '\\argmin': '\\DOTSB\\operatorname*{arg\\,min}',
 '\\bgroup': '{',
 '\\blue': '\\textcolor{##6495ed}{#1}',
 '\\blueA': '\\textcolor{##ccfaff}{#1}',
 '\\blueB': '\\textcolor{##80f6ff}{#1}',
 '\\blueC': '\\textcolor{##63d9ea}{#1}',
 '\\blueD': '\\textcolor{##11accd}{#1}',
 '\\blueE': '\\textcolor{##0c7f99}{#1}',
 '\\boxed': '\\fbox{$\\displaystyle{#1}$}',
 '\\bra': '\\mathinner{\\langle{#1}|}',
 '\\bra@ket': '<unparsed macro>',
 '\\bra@set': '<unparsed macro>',
 '\\braket': '\\mathinner{\\langle{#1}\\rangle}',
 '\\bull': '\\bullet',
 '\\char': '<function macro>',
 '\\clap': '\\mathclap{\\textrm{#1}}',
 '\\clubs': '\\clubsuit',
 '\\cnums': '\\mathbb{C}',
 '\\colon': '\\nobreak\\mskip2mu\\mathpunct{}" +\n'
            '    '
            '"\\mathchoice{\\mkern-3mu}{\\mkern-3mu}{}{}{:}\\mskip6mu\\relax',
 '\\colonapprox': '\\html@mathml{" +\n'
                  '    '
                  '"\\mathrel{\\vcentcolon\\mathrel{\\mkern-1.2mu}\\approx}}" '
                  '+\n'
                  '    "{\\mathop{\\char"3a\\char"2248}}',
 '\\coloncolon': '\\dblcolon',
 '\\coloncolonapprox': '\\Colonapprox',
 '\\coloncolonequals': '\\Coloneqq',
 '\\coloncolonminus': '\\Coloneq',
 '\\coloncolonsim': '\\Colonsim',
 '\\coloneq': '\\html@mathml{" +\n'
              '    '
              '"\\mathrel{\\vcentcolon\\mathrel{\\mkern-1.2mu}\\mathrel{-}}}" '
              '+\n'
              '    "{\\mathop{\\char"3a\\char"2212}}',
 '\\coloneqq': '\\html@mathml{" +\n'
               '    "\\mathrel{\\vcentcolon\\mathrel{\\mkern-1.2mu}=}}" +\n'
               '    "{\\mathop{\\char"2254}}',
 '\\colonequals': '\\coloneqq',
 '\\colonminus': '\\coloneq',
 '\\colonsim': '\\html@mathml{" +\n'
               '    "\\mathrel{\\vcentcolon\\mathrel{\\mkern-1.2mu}\\sim}}" +\n'
               '    "{\\mathop{\\char"3a\\char"223c}}',
 '\\copyright': '\\TextOrMath{\\textcopyright}{\\text{\\textcopyright}}',
 '\\dArr': '\\Downarrow',
 '\\darr': '\\downarrow',
 '\\dblcolon': '\\html@mathml{" +\n'
               '    '
               '"\\mathrel{\\vcentcolon\\mathrel{\\mkern-.9mu}\\vcentcolon}}" '
               '+\n'
               '    "{\\mathop{\\char"2237}}',
 '\\ddddot': '{\\overset{\\raisebox{-0.1ex}{\\normalsize ....}}{#1}}',
 '\\dddot': '{\\overset{\\raisebox{-0.1ex}{\\normalsize ...}}{#1}}',
 '\\diamonds': '\\diamondsuit',
 '\\dots': '<function macro>',
 '\\dotsc': '<function macro>',
 '\\dotso': '<function macro>',
 '\\egroup': '}',
 '\\empty': '\\emptyset',
 '\\eqcolon': '\\html@mathml{" +\n'
              '    '
              '"\\mathrel{\\mathrel{-}\\mathrel{\\mkern-1.2mu}\\vcentcolon}}" '
              '+\n'
              '    "{\\mathop{\\char"2239}}',
 '\\eqqcolon': '\\html@mathml{" +\n'
               '    "\\mathrel{=\\mathrel{\\mkern-1.2mu}\\vcentcolon}}" +\n'
               '    "{\\mathop{\\char"2255}}',
 '\\equalscolon': '\\eqqcolon',
 '\\equalscoloncolon': '\\Eqqcolon',
 '\\errmessage': '<unparsed macro>',
 '\\exist': '\\exists',
 '\\expandafter': '<function macro>',
 '\\goldA': '\\textcolor{##ffd0a9}{#1}',
 '\\goldB': '\\textcolor{##ffbb71}{#1}',
 '\\goldC': '\\textcolor{##ff9c39}{#1}',
 '\\goldD': '\\textcolor{##e07d10}{#1}',
 '\\goldE': '\\textcolor{##a75a05}{#1}',
 '\\gray': '\\textcolor{gray}{#1}',
 '\\grayA': '\\textcolor{##f6f7f7}{#1}',
 '\\grayB': '\\textcolor{##f0f1f2}{#1}',
 '\\grayC': '\\textcolor{##e3e5e6}{#1}',
 '\\grayD': '\\textcolor{##d6d8da}{#1}',
 '\\grayE': '\\textcolor{##babec2}{#1}',
 '\\grayF': '\\textcolor{##888d93}{#1}',
 '\\grayG': '\\textcolor{##626569}{#1}',
 '\\grayH': '\\textcolor{##3b3e40}{#1}',
 '\\grayI': '\\textcolor{##21242c}{#1}',
 '\\green': '\\textcolor{##28ae7b}{#1}',
 '\\greenA': '\\textcolor{##b6ffb0}{#1}',
 '\\greenB': '\\textcolor{##8af281}{#1}',
 '\\greenC': '\\textcolor{##74cf70}{#1}',
 '\\greenD': '\\textcolor{##1fab54}{#1}',
 '\\greenE': '\\textcolor{##0d923f}{#1}',
 '\\gvertneqq': '\\html@mathml{\\@gvertneqq}{≩}',
 '\\hArr': '\\Leftrightarrow',
 '\\harr': '\\leftrightarrow',
 '\\hearts': '\\heartsuit',
 '\\hspace': '\\@ifstar\\@hspacer\\@hspace',
 '\\iff': '\\DOTSB\\;\\Longleftrightarrow\\;',
 '\\image': '\\Im',
 '\\imath': '\\html@mathml{\\@imath}{ı}',
 '\\impliedby': '\\DOTSB\\;\\Longleftarrow\\;',
 '\\implies': '\\DOTSB\\;\\Longrightarrow\\;',
 '\\infin': '\\infty',
 '\\injlim': '\\DOTSB\\operatorname*{inj\\,lim}',
 '\\isin': '\\in',
 '\\jmath': '\\html@mathml{\\@jmath}{ȷ}',
 '\\kaBlue': '\\textcolor{##314453}{#1}',
 '\\kaGreen': '\\textcolor{##71B307}{#1}',
 '\\ket': '\\mathinner{|{#1}\\rangle}',
 '\\lArr': '\\Leftarrow',
 '\\lBrace': '\\html@mathml{" +\n'
             '    "\\mathopen{\\{\\mkern-3.2mu[}}" +\n'
             '    "{\\mathopen{\\char`⦃}}',
 '\\lang': '\\langle',
 '\\larr': '\\leftarrow',
 '\\liminf': '\\DOTSB\\operatorname*{lim\\,inf}',
 '\\limsup': '\\DOTSB\\operatorname*{lim\\,sup}',
 '\\llap': '\\mathllap{\\textrm{#1}}',
 '\\llbracket': '\\html@mathml{" +\n'
                '    "\\mathopen{[\\mkern-3.2mu[}}" +\n'
                '    "{\\mathopen{\\char`⟦}}',
 '\\llcorner': '\\html@mathml{\\@llcorner}{\\mathop{\\char"231e}}',
 '\\lq': '`',
 '\\lrArr': '\\Leftrightarrow',
 '\\lrarr': '\\leftrightarrow',
 '\\lrcorner': '\\html@mathml{\\@lrcorner}{\\mathop{\\char"231f}}',
 '\\lvertneqq': '\\html@mathml{\\@lvertneqq}{≨}',
 '\\maroonA': '\\textcolor{##ffbde0}{#1}',
 '\\maroonB': '\\textcolor{##ff92c6}{#1}',
 '\\maroonC': '\\textcolor{##ed5fa6}{#1}',
 '\\maroonD': '\\textcolor{##ca337c}{#1}',
 '\\maroonE': '\\textcolor{##9e034e}{#1}',
 '\\mathstrut': '\\vphantom{(}',
 '\\message': '<unparsed macro>',
 '\\mintA': '\\textcolor{##f5f9e8}{#1}',
 '\\mintB': '\\textcolor{##edf2df}{#1}',
 '\\mintC': '\\textcolor{##e0e5cc}{#1}',
 '\\minuscolon': '\\eqcolon',
 '\\minuscoloncolon': '\\Eqcolon',
 '\\minuso': '\\mathbin{\\html@mathml{" +\n'
             '    "{\\mathrlap{\\mathchoice{\\kern{0.145em}}{\\kern{0.145em}}" '
             '+\n'
             '    "{\\kern{0.1015em}}{\\kern{0.0725em}}\\circ}{-}}}" +\n'
             '    "{\\char`⦵}}',
 '\\natnums': '\\mathbb{N}',
 '\\ne': '\\neq',
 '\\neq': '\\html@mathml{\\mathrel{\\not=}}{\\mathrel{\\char`≠}}',
 '\\newcommand': '<unparsed macro>',
 '\\ngeqq': '\\html@mathml{\\@ngeqq}{≱}',
 '\\ngeqslant': '\\html@mathml{\\@ngeqslant}{≱}',
 '\\nleqq': '\\html@mathml{\\@nleqq}{≰}',
 '\\nleqslant': '\\html@mathml{\\@nleqslant}{≰}',
 '\\noexpand': '<function macro>',
 '\\not': '\\html@mathml{\\mathrel{\\mathrlap\\@not}}{\\char"338}',
 '\\notin': '\\html@mathml{\\mathrel{{\\in}\\mathllap{/\\mskip1mu}}}"\n'
            '                       + "{\\mathrel{\\char`∉}}',
 '\\notni': '\\html@mathml{\\not\\ni}{\\mathrel{\\char`∌}}',
 '\\nshortmid': '\\html@mathml{\\@nshortmid}{∤}',
 '\\nshortparallel': '\\html@mathml{\\@nshortparallel}{∦}',
 '\\nsubseteqq': '\\html@mathml{\\@nsubseteqq}{⊈}',
 '\\nsupseteqq': '\\html@mathml{\\@nsupseteqq}{⊉}',
 '\\orange': '\\textcolor{##ffa500}{#1}',
 '\\ordinarycolon': ':',
 '\\pink': '\\textcolor{##ff00af}{#1}',
 '\\plim': '\\DOTSB\\mathop{\\operatorname{plim}}\\limits',
 '\\plusmn': '\\pm',
 '\\projlim': '\\DOTSB\\operatorname*{proj\\,lim}',
 '\\providecommand': '<unparsed macro>',
 '\\purple': '\\textcolor{##9d38bd}{#1}',
 '\\purpleA': '\\textcolor{##ddd7ff}{#1}',
 '\\purpleB': '\\textcolor{##c6b9fc}{#1}',
 '\\purpleC': '\\textcolor{##aa87ff}{#1}',
 '\\purpleD': '\\textcolor{##7854ab}{#1}',
 '\\purpleE': '\\textcolor{##543b78}{#1}',
 '\\rArr': '\\Rightarrow',
 '\\rBrace': '\\html@mathml{" +\n'
             '    "\\mathclose{]\\mkern-3.2mu\\}}}" +\n'
             '    "{\\mathclose{\\char`⦄}}',
 '\\rang': '\\rangle',
 '\\rarr': '\\rightarrow',
 '\\ratio': '\\vcentcolon',
 '\\real': '\\Re',
 '\\reals': '\\mathbb{R}',
 '\\red': '\\textcolor{##df0030}{#1}',
 '\\redA': '\\textcolor{##fca9a9}{#1}',
 '\\redB': '\\textcolor{##ff8482}{#1}',
 '\\redC': '\\textcolor{##f9685d}{#1}',
 '\\redD': '\\textcolor{##e84d39}{#1}',
 '\\redE': '\\textcolor{##bc2612}{#1}',
 '\\renewcommand': '<unparsed macro>',
 '\\rlap': '\\mathrlap{\\textrm{#1}}',
 '\\rq': "'",
 '\\rrbracket': '\\html@mathml{" +\n'
                '    "\\mathclose{]\\mkern-3.2mu]}}" +\n'
                '    "{\\mathclose{\\char`⟧}}',
 '\\sdot': '\\cdot',
 '\\sect': '\\S',
 '\\set': '\\bra@set{\\{\\,}{\\mid}{}{\\,\\}}',
 '\\show': '<unparsed macro>',
 '\\simcolon': '\\mathrel{\\sim\\mathrel{\\mkern-1.2mu}\\vcentcolon}',
 '\\simcoloncolon': '\\mathrel{\\sim\\mathrel{\\mkern-1.2mu}\\dblcolon}',
 '\\spades': '\\spadesuit',
 '\\sub': '\\subset',
 '\\sube': '\\subseteq',
 '\\substack': '\\begin{subarray}{c}#1\\end{subarray}',
 '\\supe': '\\supseteq',
 '\\tealA': '\\textcolor{##94fff5}{#1}',
 '\\tealB': '\\textcolor{##26edd5}{#1}',
 '\\tealC': '\\textcolor{##01d1c1}{#1}',
 '\\tealD': '\\textcolor{##01a995}{#1}',
 '\\tealE': '\\textcolor{##208170}{#1}',
 '\\textcopyright': '\\html@mathml{\\textcircled{c}}{\\char`©}',
 '\\textregistered': '\\html@mathml{\\textcircled{\\scriptsize R}}{\\char`®}',
 '\\thetasym': '\\vartheta',
 '\\uArr': '\\Uparrow',
 '\\uarr': '\\uparrow',
 '\\ulcorner': '\\html@mathml{\\@ulcorner}{\\mathop{\\char"231c}}',
 '\\underbar': '\\underline{\\text{#1}}',
 '\\urcorner': '\\html@mathml{\\@urcorner}{\\mathop{\\char"231d}}',
 '\\varDelta': '\\mathit{\\Delta}',
 '\\varGamma': '\\mathit{\\Gamma}',
 '\\varLambda': '\\mathit{\\Lambda}',
 '\\varOmega': '\\mathit{\\Omega}',
 '\\varPhi': '\\mathit{\\Phi}',
 '\\varPi': '\\mathit{\\Pi}',
 '\\varPsi': '\\mathit{\\Psi}',
 '\\varSigma': '\\mathit{\\Sigma}',
 '\\varTheta': '\\mathit{\\Theta}',
 '\\varUpsilon': '\\mathit{\\Upsilon}',
 '\\varXi': '\\mathit{\\Xi}',
 '\\varcoppa': '\\mbox{\\coppa}',
 '\\varinjlim': '\\DOTSB\\operatorname*{\\underrightarrow{lim}}',
 '\\varliminf': '\\DOTSB\\operatorname*{\\underline{lim}}',
 '\\varlimsup': '\\DOTSB\\operatorname*{\\overline{lim}}',
 '\\varprojlim': '\\DOTSB\\operatorname*{\\underleftarrow{lim}}',
 '\\varsubsetneq': '\\html@mathml{\\@varsubsetneq}{⊊}',
 '\\varsubsetneqq': '\\html@mathml{\\@varsubsetneqq}{⫋}',
 '\\varsupsetneq': '\\html@mathml{\\@varsupsetneq}{⊋}',
 '\\varsupsetneqq': '\\html@mathml{\\@varsupsetneqq}{⫌}',
 '\\vcentcolon': '\\mathrel{\\mathop\\ordinarycolon}',
 '\\vdots': '{\\varvdots\\rule{0pt}{15pt}}',
 '\\weierp': '\\wp',
 '~': '\\nobreakspace',
 '©': '\\copyright',
 '®': '\\textregistered',
 '·': '\\cdotp',
 '‼': '\\mathclose{!\\mkern-0.8mu!}',
 'ℋ': '\\mathscr{H}',
 'ℌ': '\\mathfrak{H}',
 'ℐ': '\\mathscr{I}',
 'ℒ': '\\mathscr{L}',
 'ℛ': '\\mathscr{R}',
 'ℨ': '\\mathfrak{Z}',
 'ℬ': '\\mathscr{B}',
 'ℭ': '\\mathfrak{C}',
 'ℰ': '\\mathscr{E}',
 'ℱ': '\\mathscr{F}',
 'ℳ': '\\mathscr{M}',
 '∉': '\\notin',
 '∌': '\\notni',
 '∷': '\\dblcolon',
 '∹': '\\eqcolon',
 '≔': '\\coloneqq',
 '≕': '\\eqqcolon',
 '≘': '\\html@mathml{" +\n'
      '    "\\mathrel{=\\kern{-1em}\\raisebox{0.4em}{$\\scriptsize\\frown$}}" '
      '+\n'
      '    "}{\\mathrel{\\char`≘}}',
 '≙': '\\html@mathml{\\stackrel{\\tiny\\wedge}{=}}{\\mathrel{\\char`≘}}',
 '≚': '\\html@mathml{\\stackrel{\\tiny\\vee}{=}}{\\mathrel{\\char`≚}}',
 '≛': '\\html@mathml{\\stackrel{\\scriptsize\\star}{=}}" +\n'
      '    "{\\mathrel{\\char`≛}}',
 '≝': '\\html@mathml{\\stackrel{\\tiny\\mathrm{def}}{=}}" +\n'
      '    "{\\mathrel{\\char`≝}}',
 '≞': '\\html@mathml{\\stackrel{\\tiny\\mathrm{m}}{=}}" +\n'
      '    "{\\mathrel{\\char`≞}}',
 '≟': '\\html@mathml{\\stackrel{\\tiny?}{=}}{\\mathrel{\\char`≟}}',
 '≠': '\\neq',
 '⋮': '\\vdots',
 '⌜': '\\ulcorner',
 '⌝': '\\urcorner',
 '⌞': '\\llcorner',
 '⌟': '\\lrcorner',
 '⟂': '\\perp',
 '⟦': '\\llbracket',
 '⟧': '\\rrbracket',
 '⦃': '\\lBrace',
 '⦄': '\\rBrace',
 '⦵': '\\minuso',
 '⩴': '\\Coloneqq',
 '️': '\\textregistered'}
